language: java
before_install:
- openssl aes-256-cbc -K $encrypted_65ac47c0a6cd_key -iv $encrypted_65ac47c0a6cd_iv
  -in maven_files.tar.enc -out maven_files.tar -d
- tar xvf maven_files.tar
- mv settings.xml ~/.m2/settings.xml  
- gpg --import travis.gpg